name: Pytest-workflow
on:
  push:
    branches: [main]
    paths:
      - 'irescue/**'
      - 'tests/**'
      - '.github/workflows/pytest-workflow.yml'
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    strategy:
      matrix:
        # Python versions to add/remove: https://devguide.python.org/versions/
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: tests/config/environment.yml
          python-version: ${{ matrix.python-version }}
          condarc-file: tests/config/condarc.yml
          auto-update-conda: true
      
      - name: Install Python dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest-workflow
          python -m pip install .

      - name: Run pytest-workflow
        shell: bash -el {0}
        run: TMPDIR=~ pytest --symlink --kwdof --git-aware --color=yes

      - name: Output dependency tree
        if: success()
        shell: bash -el {0}
        run: |
          pip install --no-cache-dir pipdeptree
          pipdeptree

      - name: Output log on failure
        if: failure()
        shell: bash -el {0}
        run: |
          set -e
          echo "=== Environment Variables ==="
          env | tee /home/runner/pytest_workflow_env.log
          echo "=== Logs ==="
          cat /home/runner/pytest_workflow_*/*/log.{out,err} | tee /home/runner/pytest_workflow_combined.log
          echo "=== Tool Versions ==="
          if command -v bedtools; then bedtools --version; else echo "bedtools not found"; fi
          if command -v samtools; then samtools --version; else echo "samtools not found"; fi
          if command -v python; then python --version; else echo "python not found"; fi
          conda list -n test | tee /home/runner/pytest_workflow_conda_list.log

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4.6.0
        with:
          name: pytest_logs_py${{matrix.python-version}}_${{ github.run_id }}
          path: |
            /home/runner/pytest_workflow_*/*/log.out
            /home/runner/pytest_workflow_*/*/log.err
            /home/runner/pytest_workflow_*/*/IRescue_out
            /home/runner/pytest_workflow_*/*/IRescue_tmp
            /home/runner/pytest_workflow_env.log
            /home/runner/pytest_workflow_combined.log
            /home/runner/pytest_workflow_conda_list.log
          include-hidden-files: true
